import 'normalize.css';
import './components/style.css';
import './components/scss/fonts.scss';
import './components/scss/main.scss';
import './components/scss/header.scss';
import './components/scss/slider.scss';
import './components/scss/arcitect.scss';
import './components/scss/cooperation.scss';
import './components/scss/footer.scss';
